### ISSUE TITLE
Tullio Seems to Cause (Minor) Type Instability

### ISSUE THREAD

**Issue by ParadaCarleton** [mcabbott/Tullio.jl#112]
```
@tullio threads=false θHat := weights[x] * θHats[x]
```
Both `weights` and `θHats` were vectors of 32-bit floats, but Tullio seems to create all new floats as 64 bit floats by default. I got this to work by setting `θHat::Float32 = zero(Float32)`, but it would be nice if Tullio avoided converting types like this.

**Comment by mcabbott** [comment]
It should infer types in cases like this, although there can be bugs. This one seems to work locally:
```
julia> using Tullio

julia> weights = rand(Float32, 3); θHats = rand(Float32, 3);

julia> @tullio threads=false θHat := weights[x] * θHats[x]
0.71814775f0

julia> typeof(ans)
Float32
```

**Comment by ParadaCarleton** [comment]
Yep, looks like this was a screwup on my end. Sorry about that!
