### ISSUE TITLE
Support CUDA.jl

### ISSUE THREAD

**Issue by MasonProtter** [mcabbott/Tullio.jl#12]
Since CuArrays.jl is being replaced with CUDA.jl, it'd be good if Tullio could move it's support to CUDA.

**Comment by mcabbott** [comment]
When I tried a week ago, KernelAbstractions.jl did not yet work with CUDA.jl. But when it does, it should be easy to allow this.

**Comment by mcabbott** [comment]
Should now work on master, I think.
