### ISSUE TITLE
Unnecessary recompilations

### ISSUE THREAD

**Issue by cdsousa** [mcabbott/Tullio.jl#138]
After a package update, which included going to KernelAbstraction 0.8, I'm seeing a strange repetitive recompilation:

```julia
using CUDA, KernelAbstractions, CUDAKernels, Tullio
f(x) = 0.0
test() = ( v = CuArray(zeros(10)) ; @time @tullio v[i] = f(v #=NOTICE THIS=#) )
for _=1:4; test(); end
```

```
  1.023570 seconds (2.62 M allocations: 141.784 MiB, 3.40% gc time, 84.36% compilation time)
  0.121010 seconds (22.73 k allocations: 2.192 MiB, 32.70% compilation time)
  0.106366 seconds (22.75 k allocations: 2.192 MiB, 33.26% compilation time)
  0.115333 seconds (22.70 k allocations: 2.192 MiB, 31.22% compilation time)
```

It is the passing of `v` to `f` that triggers the behavior.

I believe this is a Tullio.jl issue, as this does not happens when using equivalent (?) KernelAbstractions.jl code:
```julia
using CUDA, KernelAbstractions, CUDAKernels
f(x) = 0.0
function test()
    @kernel k(v) = v[@index(Global)] = f(v #=NOTICE THIS=#)
    v = CuArray(zeros(10))
    @time wait(k(CUDADevice())(v, ndrange=size(v)) )
end
for _=1:4; test(); end
```

```
 18.239316 seconds (35.26 M allocations: 1.865 GiB, 3.16% gc time, 37.41% compilation time)
  0.000103 seconds (97 allocations: 3.641 KiB)
  0.000225 seconds (97 allocations: 3.641 KiB)
  0.000167 seconds (97 allocations: 3.641 KiB)
```

**Comment by glwagner** [comment]
FWIW I've seen this with kernels generated by [Oceananigans](https://github.com/CliMA/Oceananigans.jl) (unfortunately, either there's no relevant issue or I can't find it). So there may be some compiler heuristic coming into play (eg it's not _specific_ to Tullio). I can try to reproduce it if it would be helpful.

**Comment by cdsousa** [comment]
Ok, this was due to the `v` in the r.h.s. `f(v)` not being passed as a parameter to the kernel but instead being captured as a local variable.

Although this was a regression in KernelAbstractions.jl v0.8 (https://github.com/JuliaGPU/KernelAbstractions.jl/issues/293), it can be easily worked around in Tullio.jl by doing `f($v)`

```julia
using CUDA, KernelAbstractions, CUDAKernels, Tullio
f(x) = 0.0
test() = ( v = CuArray(zeros(10)) ; @time @tullio v[i] = f($v) )
for _=1:4; test(); end
```
