### ISSUE TITLE
Scalar operation on GPU on a simple operation

### ISSUE THREAD

**Issue by jeremiedb** [mcabbott/Tullio.jl#145]
The GPU version of a fairly simple operation results in (very slow) scalar operations on GPU: 

```julia
using CUDA
using Tullio

CUDA.allowscalar(false)
x1 = CUDA.rand(2,3,4)
x2 = CUDA.rand(2,3,4)
@tullio x3[j, k] := x1[i, j, k] * x2[i, j, k];
ERROR: Scalar indexing is disallowed.
```

The same kind of contractions proved to bring great speedup on CPU compared to my vanilla baseline. Does the above operations fall under a category of non-covered GPU operations?

**Comment by mcabbott** [comment]
I think it should work with `using CUDA, CUDAKernels, KernelAbstractions` -- it needs these 3 packages to define the GPU version.

**Comment by jeremiedb** [comment]
Oh, I missed that part :\ Working now with the 3 packages, sorry for the noise and thanks for those great functionalities!
