### ISSUE TITLE
Using Tullio within generated functions

### ISSUE THREAD

**Issue by JordiManyer** [mcabbott/Tullio.jl#149]
Hello, 
I've been using Tullio for some of my work, and was wondering if and how it can be used within generated functions and metaprograming. The idea is that I have a set of successive tensor contractions such as 

```julia
function func(mats,Z)
     @tullio Z[2,i1,j2] = mats[1,j1,i1] * Z[1,j1,j2]
     @tullio Z[3,i1,i2] = mats[2,j2,i2] * Z[2,i1,j2]
end
```

Both the number of tensor contractions and the number of indexes in `Z` vary depending on a dimensional parameter (in this case `N=2`). 

The idea would be to use the `@generated` functions capability in Julia in order to create different specialized functions at compile time rather than have some internal logic (these functions should be very efficient) but to be able to generate specialized functions for all possible values of `N`.  

When testing stuff to see if it is at all possible, I found that I need to be able to manipulate the index names that go into the `@tullio` macros, since each contraction affects a different index of `Z`. I have been having problem with that, and Tullio does not seem to be able to figure out what it is supposed to do. 
I was wondering if anyone had had any experience trying to implement something like this, or you might know where to start. 

Thank you!

**Comment by AriMKatz** [comment]
Does this work?

**Comment by mcabbott** [comment]
I'm sorry I missed this. 

It does not work, sadly, as the macro defines functions. The readme section "internals" explains a little bit why: in `Tullio.threader(act!, Array{T}, C, (A,B), ...)` the function `act!` is written by the macro, but `threader` depends on the runtime sizes of axes.

#129 and #11 have some discussion, I thought there was more somewhere else too.

**Comment by JordiManyer** [comment]
Yeah that is the conclusion I arrived to as well. A shame, but oh well.
