### ISSUE TITLE
Use package extensions

### ISSUE THREAD

**Issue by mcabbott** [mcabbott/Tullio.jl#164]
Julia 1.9 should allow this package to remove the use of Requires here:

https://github.com/mcabbott/Tullio.jl/blob/master/src/eval.jl#L36-L64

More ambitiously, it could also allow the present checks by the macro of whether `LoopVectorization` or `CUDA` exist in the calling scope to be replaced with something more principled.

**Comment by KristofferC** [comment]
This would indeed be nice. Tullio.jl is one of the worst packages when profiling loading https://github.com/JuliaComputing/OmniPackage.jl when it comes to time spent in `__init__` right now due to the heavy use of Requires.jl (approx 0.5 seconds spent in it).
