### ISSUE TITLE
CUDA v4 support

### ISSUE THREAD

**Issue by KristofferC** [mcabbott/Tullio.jl#172]
Since CUDA is now a weak dep and compat is properly enforced, this package can no longer be installed together with CUDA 4. Is the extension code for CUDA compatible with CUDA v4? In that case, the compat bounds could maybe be relaxed.

**Comment by mcabbott** [comment]
I don't think there should be any blocker, but will try on a GPU machine to check. For now I raised the bound on master.

I believe that before extensions, it would have been used with CUDA 4. But this would not have happened on CI, as the tests load TensorOperations, which bounds CUDA to 3.

**Comment by vpuri3** [comment]
@mcabbott could this be a regression in CUDA 4?

**Comment by vpuri3** [comment]
@mcabbott could https://github.com/mcabbott/Tullio.jl/issues/176 be a regression in CUDA 4?
