### ISSUE TITLE
Using threads, vs setting threads=false gives different result

### ISSUE THREAD

**Issue by odunbar** [mcabbott/Tullio.jl#173]
First, thanks very much for the package - It is fantastically useful in a current code I am working on. I appreciate it!

However, I am seeing discrepancies between using or not using threads.

## The issue
Is there an explanation as to why the following are different:
Running `julia v1.8.5` with `Tullio v0.3.5` and `LoopVectorization v0.12.157`

```
julia --project -t 4
``` 
then 
```julia
julia> using Tullio, LoopVectorization, LinearAlgebra # happens with or without LoopVectorization
julia> X=rand(100,200,300);
julia> @tullio x[i,j] := X[n,p,i] * X[n,p,j];
julia> @tullio threads=false y[i,j] := X[n,p,i] * X[n,p,j];
julia> norm(x-y)

# Result: 1.55e-9 [elementwise difference is approx 1e-11]

```
This is a significant difference, and I'm not sure whether the error is caused due to the use of the threading, or the functionality of disabling it. 

(My context is that I do not wish to use threading, as the tensor calculation is happening within an embarrasingly parallel loop, so I am getting linear speedups for the outer loop, hence I would like Tullio to be serialized within each iteration.)

**Comment by mcabbott** [comment]
I think this is just a consequence of doing the floating point operations in different orders. The relative errors seem quite small, since numbers in `x` are quite large:
```julia
julia> norm(x-y)
2.6970420937115938e-9

julia> norm(x)
1.5007234678784555e6

julia> (x-y)./x
300×300 Matrix{Float64}:
  1.36525e-15   3.2788e-15    1.45816e-15  …  -5.42575e-16  -1.81225e-16   1.8103e-16
  3.2788e-15    6.81041e-16  -3.11119e-15      2.54705e-15  -9.06694e-16  -2.16788e-15
  1.45816e-15  -3.11119e-15  ...
  
julia> @tullio threads=10^9 z[i,j] := X[n,p,i] * X[n,p,j];

julia> norm(x-z)
0.0
```

`threads=false` disables not just threading, but all the code for recursive blocking (which aims at being cache-friendly). I'm not entirely sure why I made it that way. Threading & blocking are part of the same recursion. 

Giving the keyword an integer `threads=N` instead sets the minimum number of steps to justify spawning a new thread (overriding a heuristic), and thus large N keeps blocking alone. Here it seems to give me identical results to `x`.

**Comment by odunbar** [comment]
Thanks very much! I also figured it was on the order rounding might be, but couldn't see why rounding would be needed which worried me about what changed when I turned of threads! 

Thanks for the simple solution too, being cache-friendly and with the added bonus of satisfying equality with 0!

**Comment by chriselrod** [comment]
> but couldn't see why rounding would be needed which worried me about what changed when I turned off threads

Rounding should generally be expected when doing floating point arithmetic.
```julia
julia> function setfpexceptions(f, mode)
           # we don't want errors from the compiler!
           f() # so we force compilation
           prev = ccall(:feenableexcept, Cint, (Cint,), mode)
           try
               f()
           finally
               ccall(:fedisableexcept, Cint, (Cint,), mode & ~prev)
           end
       end
setfpexceptions (generic function with 1 method)

julia> const FE_INEXACT    = 0x20
0x20

julia> x = Float64.(1:5);

julia> typeof(x)
Vector{Float64} (alias for Array{Float64, 1})

julia> setfpexceptions(FE_INEXACT) do
           sum(x)
       end
15.0

julia> x .= rand.();

julia> setfpexceptions(FE_INEXACT) do
           sum(x)
       end
ERROR: DivideError: integer division error
Stacktrace:
  [1] +(x::Float64, y::Float64)
    @ Base ./float.jl:409 [inlined]
  [2] add_sum(x::Float64, y::Float64)
    @ Base ./reduce.jl:27 [inlined]
  [3] _mapreduce(f::typeof(identity), op::typeof(Base.add_sum), ::IndexLinear, A::Vector{Float64})
    @ Base ./reduce.jl:443 [inlined]
  [4] _mapreduce_dim(f::typeof(identity), op::typeof(Base.add_sum), ::Base._InitialValue, A::Vector{Float64}, ::Colon)
    @ Base ./reducedim.jl:365 [inlined]
  [5] mapreduce(f::typeof(identity), op::typeof(Base.add_sum), A::Vector{Float64}; dims::Colon, init::Base._InitialValue)
    @ Base ./reducedim.jl:357 [inlined]
  [6] _sum(f::typeof(identity), a::Vector{Float64}, ::Colon; kw::Base.Pairs{Symbol, Union{}, Tuple{}, @NamedTuple{}})
    @ Base ./reducedim.jl:999 [inlined]
  [7] _sum(a::Vector{Float64}, ::Colon; kw::Base.Pairs{Symbol, Union{}, Tuple{}, @NamedTuple{}})
    @ Base ./reducedim.jl:998 [inlined]
  [8] sum(a::Vector{Float64}; dims::Colon, kw::Base.Pairs{Symbol, Union{}, Tuple{}, @NamedTuple{}})
    @ Base ./reducedim.jl:994 [inlined]
  [9] (::var"#5#6")()
    @ Main ./REPL[7]:2
 [10] setfpexceptions(f::var"#5#6", mode::UInt8)
    @ Main ./REPL[1]:5
 [11] top-level scope
    @ REPL[7]:1
```
If rounding is a concern, you can set your CPU to throw an error when rounding, like I did above.
You will probably observe it almost always does, unless you're doing something specific to avoid that, like using only integer-valued floating point numbers (if you want to do integer arithmetic but are scared of overflow, this is actually a neat trick: you can use `Float64` and check for inexact operations! `Float64` can represent all integers between -2^53 and 2^53 exactly).

This at least works on Linux with x64 CPU. I'm not sure about other platforms.

The issue you see here is just that the rounding happens slightly differently when adding numbers with a different order, not that it rounds in one case but not the other.
