### ISSUE TITLE
Use EllipsisNotation ?

### ISSUE THREAD

**Issue by jgsimard** [mcabbott/Tullio.jl#186]
would it be possible to use EllipsisNotation with this package ?

Let say we have this expression
@tullio arr[a, v, j, i, x] := A[x, k] * b[a, v, j, i, k]
could we replace it with
@tullio arr[.., x] := A[x, k] * b[.., k]

**Comment by mcabbott** [comment]
I had a go, long ago: https://github.com/mcabbott/Tullio.jl/pull/4  But it got quite complicated, and I never merged it.

**Comment by jgsimard** [comment]
something like pr #4 would be awesome! If you ever want to pick it back up, I would be very grateful! Ill check what was already done and try to improve it, but it might take me a super long time because I just started Julia!
