### ISSUE TITLE
Spurious printing of "DiffRules._abs_deriv" when LoopVectorization.jl loaded

### ISSUE THREAD

**Issue by MasonProtter** [mcabbott/Tullio.jl#26]
```julia
julia> using Tullio

julia> let v = [-1, 0, 1, 2]
           @tullio out := abs(v[i])
       end
4

julia> using LoopVectorization

julia> let v = [-1, 0, 1, 2]
           @tullio out := abs(v[i])
       end
DiffRules._abs_deriv
4

julia> typeof(ans)
Int64

julia> let v = [-1, 0, 1, 2]
           @tullio out := abs(v[i])
       end
DiffRules._abs_deriv
4
```
Is this maybe some `println` debugging that didn't get removed?

**Comment by mcabbott** [comment]
What's going on is that it tries to expand `@avx` within a try-catch block, and for the gradient it fails:
```julia
julia> let v = [-1, 0, 1, 2]
           @tullio out := abs(v[i])  verbose=true
       end
┌ Info: symbolic gradients
│   inbody =
│    1-element Array{Any,1}:
└     :(𝛥v[i] = 𝛥v[i] + conj(conj(𝛥ℛ[1]) * DiffRules._abs_deriv(v[i])))
DiffRules._abs_deriv
┌ Warning: LoopVectorization failed  (symbolic gradient)
│   err =
│    LoadError: "Expression not recognized."
│    in expression starting at /Users/me/.julia/packages/Tullio/MpOl9/src/macro.jl:856
└ @ Tullio ~/.julia/packages/Tullio/MpOl9/src/macro.jl:864
```
And just before it fails, it helpfully prints out the problematic expression:
https://github.com/chriselrod/LoopVectorization.jl/blob/c21c174f0f6676ea9098e632d9bd79e5fb51e885/src/graphs.jl#L606

It seems a little un-Junlian to need try/catch, but it seems otherwise hard to predict what will or won't work. I'm not even sure why it dislikes `_abs_deriv`, which is from here
https://github.com/JuliaDiff/DiffRules.jl/blob/c97ee0b8a7431a7d707e3a6bcb66de76fdc240b1/src/rules.jl#L68
but it certainly doesn't work:
```julia
julia> let v = [-1, 0, 1, 2]
           @tullio a[i] := Tullio.DiffRules._abs_deriv(b[i]) 
       end
ERROR: TypeError: non-boolean (VectorizationBase.Mask{4,UInt8}) used in boolean context
Stacktrace:
 [1] _abs_deriv at /Users/me/.julia/packages/DiffRules/5QwtC/src/rules.jl:72 [inlined]

```

**Comment by mcabbott** [comment]
This particular case is silenced by https://github.com/mcabbott/Tullio.jl/commit/3d6d67793c416b0d84d491dac0ee83ac1ec758d8.

**Comment by MasonProtter** [comment]
Hm, won't there be a performance overhead from the `try-catch`?

**Comment by mcabbott** [comment]
Sure, but I don't think it's the biggest concern. On a fresh session, it takes about this long to run the macro:
```
julia> using Tullio

julia> A = rand(10); B = similar(A);

julia> @time @tullio B[i] = A[i]^2;
  0.182469 seconds (601.81 k allocations: 30.120 MiB)

julia> @time @tullio B[i] = A[i]^2;
  0.145392 seconds (351.19 k allocations: 17.040 MiB)
```
and with LoopVectorization:
```jullia
julia> using Tullio, LoopVectorization

julia> A = rand(10); B = similar(A);

julia> @time @tullio B[i] = A[i]^2;
  1.526361 seconds (2.83 M allocations: 136.745 MiB, 2.74% gc time)

julia> @time @tullio B[i] = A[i]^2;
  0.262372 seconds (677.75 k allocations: 28.234 MiB)
```
I would love this to be quicker, but don't know how. Slightly sad comparison:
```
julia> using Einsum

julia> @time @einsum B[i] = A[i]^2;
  0.011006 seconds (1.44 k allocations: 88.536 KiB)

julia> @time @einsum B[i] = A[i]^2;
  0.000014 seconds (31 allocations: 672 bytes)
```

**Comment by MasonProtter** [comment]
Oh, I didn't realize the `try-catch` was being run at macroexpansion time, I thought it was runtime, my mistake! I'm not at *all* concerned about the macroexpansion or compile times of Tullio.
