### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by ranocha** [mcabbott/Tullio.jl#39]
I noticed that this repo still uses travic-ci.org, at least based on the badge in the README. travis-ci.org will be shut down at the end of the year, cf. https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom. Hence, everything should be migrated to travis-ci.com.

**Comment by mcabbott** [comment]
Thanks for the reminder. I did some packages when someone else reminded me, and then didn't get back to the others...
