### ISSUE TITLE
Unexpected behaviour when summing with different sign

### ISSUE THREAD

**Issue by roflmaostc** [mcabbott/Tullio.jl#44]
Hey,

I recognized the following today. The only difference between correct one and wrong one are the signs.
```
julia> using Tullio
julia> arr = [1 2; 1 2; 3 4; 3 4]
4×2 Array{Int64,2}:
 1  2
 1  2
 3  4
 3  4
julia> @tullio x2[i1, i2] := (arr[2i1 + 1, 2i2 + 1] + arr[2i1 + 0, 2i2 + 1] + arr[2i1 + 1, 2i2 + 0] + arr[2i1 + 0, 2i2 + 0])
1×0 Array{Int64,2}
julia> @tullio x2[i1, i2] := (arr[2i1 - 1, 2i2 - 1] + arr[2i1 + 0, 2i2 - 1] + arr[2i1 - 1, 2i2 + 0] + arr[2i1 + 0, 2i2 + 0])
2×1 Array{Int64,2}:
  6
 14
```

I didn't expect this because your downsample example is also formulated in a "+" way.

Thanks,

Felix

Edit: I guess I understand it. It simply starts at i1=1 and then sums up from there (3 + 1).
So that's wanted behaviour?

**Comment by mcabbott** [comment]
Yes I think this is the correct behaviour. Here's another way to see it, same expressions:
```julia
julia> arr = rand(100,200);

julia> size(@tullio x2[i1, i2] := (arr[2i1 + 1, 2i2 + 1] + arr[2i1 + 0, 2i2 + 1] + arr[2i1 + 1, 2i2 + 0] + arr[2i1 + 0, 2i2 + 0])  verbose=true grad=false threads=false)
┌ Info: left index ranges
│   i1 = 1:49
└   i2 = 1:99
(49, 99)

julia> size(@tullio x2[i1, i2] := (arr[2i1 - 1, 2i2 - 1] + arr[2i1 + 0, 2i2 - 1] + arr[2i1 - 1, 2i2 + 0] + arr[2i1 + 0, 2i2 + 0])  verbose=true grad=false threads=false)
┌ Info: left index ranges
│   i1 = 1:50
└   i2 = 1:100
(50, 100)
```
`2i1 + const` means the range of `i1` has to be about half of `size(arr,1)`, which it is. In fact the range is something like `i1 in (axes(arr,1) .- const) ./ 2`, but this division has to be done carefully. In all of these cases, the previous/next integer not included in the ranges it chose would put you outside of `axes(arr,1)` in one of the terms.

**Comment by roflmaostc** [comment]
Thanks for your explanation, it seems very reasonable :smiling_face_with_three_hearts: 

I'll close that issue.
