### ISSUE TITLE
Macro hygiene issue `ndims`

### ISSUE THREAD

**Issue by MasonProtter** [mcabbott/Tullio.jl#46]
Observe this initially baffling bit of code:
```julia
julia> using Tullio

julia> let s = [1,2,3,4]
           @tullio x[i] := s[i]
       end
4-element Array{Int64,1}:
 1
 2
 3
 4

julia> let s = [1,2,3,4], ndims=maximum(s)
           @tullio x[i] := s[i]
       end
ERROR: MethodError: objects of type Int64 are not callable
Stacktrace:
 [1] top-level scope at /home/mason/.julia/packages/Tullio/Q2RDS/src/macro.jl:970
 [2] top-level scope at REPL[3]:2
```
I think somewhere in the macroexpansion, you need to interpolate the `Tullio.ndims` function otherwise a user having a variable called `ndims` causes trouble.

**Comment by mcabbott** [comment]
Thanks, there are probably a bunch of these, like `eachindex` or `axes`. It's probably overdue for a thorough scrubbing.
