### ISSUE TITLE
Error requiring LoopVectorization from Tullio

### ISSUE THREAD

**Issue by jondeuce** [mcabbott/Tullio.jl#51]
I get the following warning on Tullio v0.2.10 when loading LoopVectorization v0.9.1:

```julia
┌ Warning: Error requiring LoopVectorization from Tullio:
│ UndefVarError: SVec not defined
...
```

I believe it is due to the renaming of an internal struct `SVec` in [previous versions](https://github.com/chriselrod/VectorizationBase.jl/blob/72d8e79245b7cf5b1bb86a5253bbd7742951b158/src/VectorizationBase.jl#L46) of VectorizationBase to `Vec` in [current versions](https://github.com/chriselrod/VectorizationBase.jl/blob/b83f186d6f3fddb625f49256500c958b23b56518/src/VectorizationBase.jl#L70).

I'm not familiar enough with your internals to make a PR to fix this, but naively it looks like a simple find and replace.

**Comment by mcabbott** [comment]
On master there's a quick attempt at a fix, much like you suggest: https://github.com/mcabbott/Tullio.jl/commit/7896059b78a737a467af881d2afb3e36986af7a7

The awkward bit about using Requires is that we can't let Pkg bound versions. But maybe this is simple enough to just work. Needs to be tested a bit more...

**Comment by jondeuce** [comment]
Thanks for the quick response! Ahh yes, I see the problem, that's a bit of a sticky situation. Your fix appears to have worked for the original issue, but now I receive a similar warning when loading `ForwardDiff`:

```julia
┌ Warning: Error requiring ForwardDiff from Tullio:
│ LoadError: UndefVarError: SVec not defined
│ ...
│ in expression starting at /home/.julia/packages/Tullio/JZOUh/src/grad/avxdual.jl:6
```

It seems like another small change should fix this, too; the culprit should be [this line](https://github.com/mcabbott/Tullio.jl/blob/7896059b78a737a467af881d2afb3e36986af7a7/src/grad/avxdual.jl#L6).

**Comment by mcabbott** [comment]
Thanks for testing... mostly I should comment out the worked example in that file! With latest commit: 
```
julia> using Tullio, ForwardDiff, LoopVectorization, Tracker

julia> r33 = rand(3,3);

julia> Tracker.gradient(x -> sum(@tullio y[i] := log(x[i,j])), r33)
([1.1394564210213642 2.1680893862937927 1.0559383908137436; 1.1351873479437349 6.481911983174566 14.998379183695935; 1.85023371959207 19.48339920489614 1.0349811616209528] (tracked),)

julia> Tracker.gradient(x -> sum(@tullio y[i] := log(x[i,j]) grad=Dual), r33)
([1.1394564210213642 2.1680893862937927 1.0559383908137436; 1.1351873479437349 6.481911983174566 14.998379183695935; 1.85023371959207 19.48339920489614 1.0349811616209528] (tracked),)
```

**Comment by chriselrod** [comment]
You're not the first person to have issues from the renaming. It'd be nice if optional dependencies could specify bounds.

Maybe I should have defined:
```julia
const SVec = Vec
```

**Comment by jondeuce** [comment]
Great - seems like everything is working on my end :+1:.

@chriselrod I believe that would have been sufficient in this case, though cluttering up your package's namespace is not ideal. But as you say, specifying bounds on optional dependencies (and generally being able to test different versions of optional dependencies more easily) would be much better.

**Comment by AshtonSBradley** [comment]
so... what is the fix?

**Comment by mcabbott** [comment]
@AshtonSBradley the solution is to use master for now, as in `] add Tullio#master`. There's a fix but I wanted to test it a bit more carefully before tagging.

@chriselrod no problem at all, this is a pretty minimal level of hassle. Thanks for sorting out the 1.6 update.
