### ISSUE TITLE
besselj0 error

### ISSUE THREAD

**Issue by AshtonSBradley** [mcabbott/Tullio.jl#54]
Code that used to work on 1.5.3 and still works with e.g. `sin`

```julia
k = LinRange(.16,37.8,Np) |> collect
rv = LinRange(0,15,1000) |> collect
gvec = zero(rv)

@tullio gvec[i] = rv[i]*sin(k[j]*rv[i])
```
and used to work with `besselj0` now fails  
```julia
@tullio gvec[i] = rv[i]*besselj0(k[j]*rv[i])
ERROR: LoadError: StackOverflowError:
Stacktrace:
 [1] besselj0(x::VectorizationBase.Vec{4, Float64})
   @ SpecialFunctions ~/.julia/packages/SpecialFunctions/24S26/src/bessel.jl:204
in expression starting at /Users/abradley/Dropbox/Research/Projects/GPESpectra/scripts/2d_trap_correlation_spectra.jl:760
```

**Comment by chriselrod** [comment]
It should work if you set `avx=false`.

**Comment by AshtonSBradley** [comment]
what does this mean? no LoopVectorization?

**Comment by AshtonSBradley** [comment]
strangely, I have code elsewhere that still works with `besselj0` and `avx`. How do I know what is broken here?

**Comment by chriselrod** [comment]
Yes, that means no LoopVectorization.
Maybe `LoopVectorization.check_args` returns `false` for some of the inputs on the cases that do work?

**Comment by mcabbott** [comment]
Minimal test BTW seems to be this:
```julia
julia> using LoopVectorization, SpecialFunctions                             

julia> @avx besselj0.(rand(3))                                               
ERROR: StackOverflowError:
Stacktrace:
 [1] besselj0(::Vec{4,Float64}) at /Users/me/.julia/packages/SpecialFunctions/24S26/src/bessel.jl:204 (repeats 79984 times)
```
and the offending method is `::Real` here:
```julia
# besselj0, besselj1, bessely0, bessely1
for jy in ("j","y"), nu in (0,1)
...
    bjynu = Symbol("bessel",jy,nu)
    if jy == "y"
...
    else
        @eval begin
            $bjynu(x::Float64) = ccall(($jynu,libm),  Float64, (Float64,), x)
            $bjynu(x::Float32) = ccall(($jynuf,libm), Float32, (Float32,), x)
            $bjynu(x::Float16) = Float16($bjynu(Float32(x)))
        end
    end
    @eval begin
        $bjynu(x::Real) = $bjynu(float(x))
        $bjynu(x::Complex) = $(Symbol("bessel",jy))($nu,x)
    end
...
```

**Comment by chriselrod** [comment]
Special functions that aren't defined in [SLEEFPirates.jl](https://github.com/chriselrod/SLEEFPirates.jl) are probably not going to work.

**Comment by AshtonSBradley** [comment]
As a starting point, is there a stuitable method in the package that SLEEFPirates.jl replaces?

**Comment by chriselrod** [comment]
I'm not sure what you mean, what sort of method do you have in mind?

You'd want to define `besselj0(::Vec{W,Float64}) where {W}`.
Unfortunately, that'd be `SLEEFPirates.besselj0` instead of `SpecialFunctions.besselj0`.
We'd have to pick a place to define them.

**Comment by mcabbott** [comment]
Closing this as it's not really a Tullio.jl issue.
