### ISSUE TITLE
Migrate GPU CI to Buildkite?

### ISSUE THREAD

**Issue by DilumAluthge** [mcabbott/Tullio.jl#56]
Right now, Tullio.jl uses the GitLab runners for running GPU CI in the JuliaGPU group.

If I understand correctly, JuliaGPU is transitioning from GitLab to Buildkite, with the plan of eventually completely discontinuing the GitLab runners.

It would be great to migrate the GPU CI for Tullio.jl from the GitLab runners to the Buildkite runners.

@maleadt Can you provide instructions for migrating to the new Buildkite JuliaGPU setup?

**Comment by mcabbott** [comment]
Agree this would be good. I spent a few minutes following https://discourse.julialang.org/t/juliagpu-ci-moving-to-buildkite/49925 but didn't get to the bottom of it, and meant to look again at some point.

**Comment by DilumAluthge** [comment]
This is probably a good place to start:
- https://github.com/JuliaGPU/KernelAbstractions.jl/blob/master/.buildkite/pipeline.yml
