### ISSUE TITLE
Different results: for loop vs Tullio

### ISSUE THREAD

**Issue by roflmaostc** [mcabbott/Tullio.jl#7]
Hey,

the code below produces different results when using Tullio and for loops. Once I'm using Float64 the results are very close to each other. Is this due to @fastmath? If yes, can we disable it?

Thanks,

Felix

```
using TestImages
using Tullio
img = convert(Array{Float32}, testimage("fabio_gray_512"))
x = reshape(img, 512, 512)

@tullio res_t = (x[i + 1, j] + x[i - 1, j])^2 (i in 2:size(x)[1] - 1)
print(res_t, "\n")

@tullio res_t = (x[i + 1, j] + x[i - 1, j])^2
print(res_t, "\n")

res_f = 0
for i = 2:size(x)[1] -1
    for j = 1:size(x)[2]
        res_f += (x[i+1, j] + x[i - 1, j])^2
    end
end
print(res_f)
```
output:
```
219891.22
219891.22
219914.31
```

**Comment by mcabbott** [comment]
Thanks for stress-testing this thing. I think that what's going on here is just rounding errors from adding things up in different orders. Notice that changing the loop order changes the result, and that my `@tullio` result is different to yours, probably because the division of work among threads is different. 

```julia
f_loop(x)   # 219914.31f0  -- as in post above
f_loop(x64) # 219891.42109962495

# same with @fastmath, no change:

f_fast(x)   # 219914.31f0
f_fast(x64) # 219891.42109962495

function f_rev(x)
    res_f = zero(eltype(x))
    for j = 1:size(x)[2]
        for i = 2:size(x)[1] -1
            res_f += (x[i+1, j] + x[i - 1, j])^2
        end
    end
    res_f
end

f_rev(x)   # 219916.52f0
f_rev(x64) # 219891.42109964453

@tullio res_t = (x[i + 1, j] + x[i - 1, j])^2        # 219891.95f0 -- compare 219891.22
@tullio res_t_64 = (x64[i + 1, j] + x64[i - 1, j])^2 # 219891.4210995792

using LoopVectorization

@tullio res_lv = (x[i + 1, j] + x[i - 1, j])^2        # 219891.44f0
@tullio res_lv_64 = (x64[i + 1, j] + x64[i - 1, j])^2 # 219891.42109957797
```

There is not an option to disable `@fastmath` right now, perhaps I should add one. It might also be good to always accumulate scalar sums as Float64, for better accuracy?

**Comment by roflmaostc** [comment]
Thanks for the quick answer, yes you're right. Changing the order changes the result, however it's not as drastic as the change of the Tullio variant.
But since Float64 seems to be correct, I think it's fine!

At the moment I'm developing a package which relies on Tullio, so I would be thankful if you continue your work :laughing: 
If I'll find some other stuff, I would let you know. The plan is to use 5D arrays with Tullio in combination with FFTs, CUDA, etc. So we will see :smiley:

**Comment by mcabbott** [comment]
Great, let me know if you run into other issues. I will register it fairly soon.
