### ISSUE TITLE
Potential for race conditions with shifted indices

### ISSUE THREAD

**Issue by mcabbott** [mcabbott/Tullio.jl#85]
This doesn’t look thread safe in the gradient, as one thread’s `i+1` may be another’s `i`:
```julia
julia> using Tullio

julia> reg(x) = @tullio res = sqrt(abs2(x[i, j] - x[i+1, j]) +abs2(x[i, j] - x[i, j+1])) verbose=2
...
┌ Info: symbolic gradients
│   inbody =
│    3-element Array{Any,1}:
│     :(𝛥x[i, j] = 𝛥x[i, j] + 𝛥ℛ[1] * conj((((x[i, j] - x[i + 1, j]) + (x[i, j] - x[i + 1, j])) + ((x[i, j] - x[i, j + 1]) + (x[i, j] - x[i, j + 1]))) * (inv(sqrt(abs2(x[i, j] - x[i + 1, j]) + abs2(x[i, j] - x[i, j + 1]))) / 2)))
│     :(𝛥x[i + 1, j] = 𝛥x[i + 1, j] + 𝛥ℛ[1] * conj(-(((x[i, j] - x[i + 1, j]) + (x[i, j] - x[i + 1, j]))) * (inv(sqrt(abs2(x[i, j] - x[i + 1, j]) + abs2(x[i, j] - x[i, j + 1]))) / 2)))
└     :(𝛥x[i, j + 1] = 𝛥x[i, j + 1] + 𝛥ℛ[1] * conj(-(((x[i, j] - x[i, j + 1]) + (x[i, j] - x[i, j + 1]))) * (inv(sqrt(abs2(x[i, j] - x[i + 1, j]) + abs2(x[i, j] - x[i, j + 1]))) / 2)))
┌ store.
│   arrays = [:x]
…
│   sharedind = [:i, :j]
│   shiftedind = [:i, :j]
```
Example from https://discourse.julialang.org/t/fast-gpu-kernels-differentiable-with-zygote/56756 (mostly about scalar reductions on GPU)

**Comment by roflmaostc** [comment]
So you mean the gradients could be wrong?

Because I'm observing certain artifacts in my deconvolution using the same regularizer on GPU vs on CPU. So something with the GPU might be wrong.

Here a MWE:
```julia
using Tullio, CUDA, KernelAbstractions, Zygote, TestImages

reg(x) = sum(@tullio res[i, j] := abs2(x[i, j] - x[i, j+1]) +  abs2(x[i, j] - x[i+1, j]))


x = Float32.(testimage("resolution_test_512"))
x_c = CuArray(x);

y1 = Zygote.gradient(reg, x)[1]
y2 = Zygote.gradient(reg, x_c)[1]
.≈(y1, Array(y2), rtol=0.01)[100:110, 100:110]
```
Returns 
```julia
11×11 BitMatrix:
 1  0  1  1  1  0  0  1  1  0  1
 1  0  1  1  1  0  0  1  1  0  1
 1  0  1  1  1  0  0  1  1  0  1
 1  0  1  1  1  0  0  1  1  0  1
 1  0  1  1  1  0  0  1  1  0  1
 1  0  1  1  1  0  0  1  1  0  1
 1  0  1  1  1  0  0  1  1  0  1
 1  0  1  1  1  0  0  1  1  0  1
 1  0  1  1  1  0  0  1  1  0  1
 1  0  1  1  1  0  0  1  1  0  1
 1  0  1  1  1  0  0  1  1  0  1
```
So the gradient might be broken, showing some column patterns.

**Comment by mcabbott** [comment]
Thanks for doing the test. Yes, I do think this can give incorrect gradients, sadly. Somehow I didn't think of this case before.

The obvious fix would be that, when `i` appears with two different shifts, it should be marked "unsafe" for the gradient calculation. (There are already some situations where the macro notices this.) However, in this example, marking both `i` and `j` unsafe would mean the entire gradient calculation has to run serially, which will be awful on the GPU. 

A possible work-around would be to pretend that the different terms are separate arrays. Then it will accumulate the gradients into `𝛥x`, `𝛥x2`, `𝛥x3` and Zygote will combine them afterwards: ``` reg2(x) = begin
  x2 = x
  x3 = x
  sum(@tullio res[i, j] := abs2(x[i, j] - x2[i, j+1]) +  abs2(x[i, j] - x3[i+1, j]))
end ```

**Comment by roflmaostc** [comment]
Ok, the workaround seems to work. I'll probably stick with it for now!
Thanks, your support is exceptional great! :)

**Comment by roflmaostc** [comment]
So this affects both CPU and GPU, correct?

**Comment by mcabbott** [comment]
Yes. But I think it's much harder to get a wrong answer on the CPU, as there are fewer threads, which is probably why I didn't notice. For `res` above, if this testimage is divided 4 ways, and they all start at the top left, they are very unlikely to fight each other. 

There might be other functions which behave much worse, maybe something like `x[end-i]` instead of `x[i+1]`? But this doesn't seem to:
```julia
julia> f2(x) = sum(@tullio out[i] := x[i] + sqrt(x[20-i]) threads=2);  # 2 is the threshold to divide among threads

julia> Zygote.gradient(f2, 1:20)[1] ≈ ForwardDiff.gradient(f2, 1:20)   # all 4 threads work on these 20 elements
true
```

**Comment by roflmaostc** [comment]
Yeah, I agree. Could be wrong but unlikely to happen and if, only affecting a minor amount of pixels.
